# This file configures the analyzer to use the lint rule set from `package:flutter_lints`

include: package:flutter_lints/flutter.yaml

linter:
  # The lint rules applied to this project can be customized in the
  # section below to disable rules from the `package:flutter_lints/flutter.yaml`
  # included above or to enable additional rules. A list of all available lints
  # and their documentation is published at
  # https://dart-lang.github.io/linter/lints/index.html.
  rules:
    # avoid_print: false  # Uncomment to disable the `avoid_print` rule
    # prefer_single_quotes: true  # Uncomment to enable the `prefer_single_quotes` rule
    prefer_const_constructors: true
    prefer_const_declarations: true
    avoid_empty_else: true
    avoid_relative_lib_imports: true
    avoid_returning_null_for_future: true
    avoid_slow_async_io: true
    avoid_types_as_parameter_names: true
    cancel_subscriptions: true
    close_sinks: true
    control_flow_in_finally: true
    empty_statements: true
    no_duplicate_case_values: true
    prefer_void_to_null: true
    throw_in_finally: true

analyzer:
  # For more information about the core and recommended set of lints, see
  # https://dart.dev/go/core-lints

  # The following line activates a set of recommended lints for Flutter apps,
  # packages, and plugins designed to encourage good coding practices.
  language:
    strict-casts: true
    strict-raw-types: true

  errors:
    # treat missing required parameters as a warning (not a hint)
    missing_required_param: warning
    # treat missing returns as a warning (not a hint)
    missing_return: warning
    # allow having TODOs in the code
    todo: ignore

  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"